#!/bin/bash

#PBS -N CJ_create_and_test
#PBS -l select=1:ncpus=8:mem=64gb
#PBS -l walltime=12:00:00

#PBS -j oe
#PBS -M christopher.jin@unsw.edu.au
#PBS -m ae

cd /srv/scratch/z5312523/CJ_deepfri_from_seq

source /srv/scratch/z5312523/Miniconda3/etc/profile.d/conda.sh

conda create --name deepfri python=3.7
conda activate deepfri
mkdir models
cd models
wget https://users.flatironinstitute.org/~renfrew/DeepFRI_data/newest_trained_models.tar.gz
cd ..
wget https://github.com/flatironinstitute/DeepFRI/archive/refs/heads/master.zip
unzip master.zip
rm master.zip
mv DeepFRI-master/ deepfri_from_seq
tar -xvzf models/newest_trained_models.tar.gz -C deepfri_from_seq
mv deepfri_from_seq/README.md deepfri_from_seq/README_deepfri.md
mkdir deepfri_from_seq/results
cp deepfri_from_seq/seq2pdb/* deepfri_from_seq/
rm -r deepfri_from_seq/seq2pdb
cp -r !(deepfri_from_seq) /deepfri_from_seq
ls | grep -xv "deepfri_from_seq/" | parallel rm -r
cd deepfri_from_seq/
pip install .
python CJ_deepfri_from_seq.py -o test -s SMTDLLSAEDIKKAIGAFTAADSFDHKKFFQMVGLKKKSADDVKKVFHILDKDKDGFIDEDELGSILKGFSSDARDLSAKETKTLMAAGDKDGDGKIGVEEFSTLVAES